### ISSUE TITLE
ZSH Issue

### ISSUE THREAD

**Issue by vitali-shcharbin** [johnnyopao/awsp#3]
I have AWS CLI installed, ZSH, Iterm2. After running:
```
awsp
```

Getting following error:
```
AWS Profile Switcher
No profiles found.
Refer to this guide for help on setting up a new AWS profile:
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
Error: TypeError: Cannot read property 'profile' of undefined
    at writeToConfig (/usr/local/lib/node_modules/awsp/index.js:57:17)
cat: /Users/***/.awsp: No such file or directory
```

Do you know what could be the issue?

**Comment by Le0exxx** [comment]
Hi Vitail,

    I hit the same issue, how did you fix it?

Rds,
Leo

**Comment by vitali-s** [comment]
Le0exxx, I don't remember exactly, but it was some basic configuration, maybe:
```
alias awsp="source _awsp"
```

Later I've replaced it with simple sed+fzf alias:
```
alias aws-profile='export AWS_PROFILE=$(sed -n "s/^\[profile \(.*\)\]/\1/gp" ~/.aws/config | fzf)'
```

**Comment by kolesnevg** [comment]
@Le0exxx in ~/.aws/config profile section name should have "profile" prefix
[development] will throw error
[profile development] success
